# Generated by Django 2.2.2 on 2020-01-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('pseudo', models.CharField(blank=True, max_length=30)),
                ('localisation', models.CharField(default='fr', max_length=2)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('interests', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('duration', models.DurationField(blank=True)),
                ('company', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('IT-L', 'Langage de programation'), ('IT-T', 'Outils de programation'), ('IT-S', 'Systèmes Informatique'), ('FH', 'Humaine'), ('O', 'Other')], max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('icon', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='XP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('is_scolarship', models.BooleanField(default=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
